{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "%matplotlib inline\n",
    "from matplotlib import style\n",
    "style.use('fivethirtyeight')\n",
    "import matplotlib.pyplot as plt\n",
    "\n",
    "import numpy as np\n",
    "import pandas as pd\n",
    "\n",
    " import datetime\n",
    "\n",
    " import sqlalchemy\n",
    "from sqlalchemy.ext.automap import automap_base\n",
    "from sqlalchemy.orm import Session\n",
    "from sqlalchemy import create_engine, func\n",
    "\n",
    "from flask import Flask, jsonify\n",
    "\n",
    "#connect engine to sqlite\n",
    "engine = create_engine(\"sqlite:///Resources/hawaii.sqlite\")\n",
    "# reflect an existing database into a new model\n",
    "Base = automap_base()\n",
    "# reflect the tables\n",
    "Base.prepare(engine, reflect=True)\n",
    "Base.classes.keys()\n",
    " # Save references to each table\n",
    "Measurement = Base.classes.measurement\n",
    "Station = Base.classes.station\n",
    "# Create our session (link) from Python to the DB\n",
    "session = Session(engine)\n",
    "#######################################\n",
    "#flask setup\n",
    "#######################################\n",
    "app=Flask(_name_)\n",
    "#######################################\n",
    "#flask routes\n",
    "#######################################\n",
    "#Have the home page return the information of the different routes\n",
    "@app.route(\"/\")\n",
    "#list all routes\n",
    "return (\n",
    "f\"<p>All routes available:</p>\"\n",
    "f\"/api/v1.0/precipitation<br/>Returns a JSON representation of percipitation data for the dates between 2016-08-23 to 2017-07-10/>\"\"\n",
    "f\"/api/v1.0/stations<br/>Returns a JSON list of the weather stations<br/><br/>\"\n",
    "f\"/api/v1.0/tobs<br/>Returns a JSON list of the Temperature Observations (tobs) for each station for the dates between {last_12mnth} and {last_date[0][0]}<br/><br/>\"\n",
    "f\"/api/v1.0/<start>Returns a JSON list of the minimum temperature, the average temperature, and the max temperature for a given start or start-end range/>\"\n",
    "f\"/api/v1.0/<start>/<end>Returns a JSON list of the minimum temperature, the average temperature, and the max temperature for a given start or start-end range/>\"\n",
    ")\n",
    "#############################################################\n",
    "@app.route(\"/api/v1.0/precipitation\")\n",
    "def precipitation():\n",
    "    print(\"precipitation status:OK\")\n",
    "    #query to retrieve the last 12 months of precipitation data.\n",
    "    results = session.query(Measurement.date, Measurement.prcp).filter(Measurement.date >= last_year).all()\n",
    "    #Convert the query results to a Dictionary using date as the key and prcp as the value.\n",
    "    prcp_totals = []\n",
    "    for result in results:\n",
    "        row = {}\n",
    "        row[\"date\"] = result[0]\n",
    "        row[\"prcp\"] = result[1]\n",
    "        prcp_totals.append(row)\n",
    "    #Return the JSON representation of your dictionary.\n",
    "    return jsonify(prcp_totals)\n",
    " #########################################################\n",
    "@app.route(\"/api/v1.0/stations\")\n",
    "def station():\n",
    "    print(\"station status:OK\")\n",
    "    #a query to get the stations.\n",
    "    stations_query = session.query(Station.station, func.count(Measurement.id)).select_from(Measurement).\\\n",
    "    join(Station, Measurement.station == Station.station).group_by(Station.station).\\\n",
    "    order_by(func.count(Measurement.id).desc()).all()\n",
    "    stations = pd.read_sql(stations_query.statement, stations_query.session.bind)\n",
    "    #Return a JSON list of stations from the dataset.\n",
    "    return jsonify(stations.to_dict())\n",
    "#########################################################\n",
    "@app.route(\"/api/v1.0/tobs\")\n",
    "def tobs():\n",
    "\tprint(\"tobs status:OK\")\n",
    "\t#query for the dates and temperature observations from a year from the last data point\n",
    "\ttobs_results = session.query(func.min(Measurement.tobs), func.max(Measurement.tobs), func.avg(Measurement.tobs)).\\\n",
    "    filter(Measurement.station == most_active_station).all()\n",
    "    # Create a list of dicts with `date` and `tobs` as the keys and values\n",
    "\ttobs_totals = []\n",
    "\tfor result in tobs_results:\n",
    "\t\trow = {}\n",
    "\t\trow[\"date\"] = result[0]\n",
    "\t\trow[\"tobs\"] = result[1]\n",
    "\t\ttobs_totals.append(row)\n",
    "\t#Return a JSON list of Temperature Observations (tobs) for the previous year.\n",
    "\treturn jsonify(tobs_totals)\n",
    "#######################################################\n",
    "@app.route(\"/api/v1.0/<start>\")\n",
    "def start_date(start):\n",
    "\tprint(\"start_date status:OK\")\n",
    "\tstart_date = dt.datetime.strptime(start, '%Y-%m-%d').date()\n",
    "\tlast_date_dd = (dt.datetime.strptime(last_date[0][0], '%Y-%m-%d')).date() \n",
    "\tfirst_date_dd = (dt.datetime.strptime(first_date[0][0], '%Y-%m-%d')).date()\n",
    "\t#start_date greater or less than\n",
    "\tif start_date > last_date_dd or start_date < first_date_dd:\n",
    "\t\treturn(f\"Select date range between {first_date[0][0]} and {last_date[0][0]}\")\n",
    "\telse:\n",
    "\t\t#Return a JSON list of the minimum temperature, the average temperature, \n",
    "\t\t#and the max temperature for a given start range.\n",
    "\t\tstart_min_max_temp = return session.query(func.min(Measurement.tobs), func.avg(Measurement.tobs), func.max(Measurement.tobs)).\\\n",
    "        filter(Measurement.date >= start_date).filter(Measurement.date <= end_date).all()\n",
    "        start_date_data = list(np.ravel(start_min_max_temp))\n",
    "\t\treturn jsonify(start_date_data)\n",
    "##########################################################\n",
    "@app.route(\"/api/v1.0/<start>/<end>\")\n",
    "def end_date(start,end):\n",
    "\tprint(\"start and end status:OK\")\n",
    "\tstart_date = dt.datetime.strptime(start, '%Y-%m-%d').date()\n",
    "\tend_date = dt.datetime.strptime(end, '%Y-%m-%d').date()\n",
    "\tlast_date_dd = (dt.datetime.strptime(last_date[0][0], '%Y-%m-%d')).date() \n",
    "\tfirst_date_dd = (dt.datetime.strptime(first_date[0][0], '%Y-%m-%d')).date()\n",
    "\tif start_date > last_date_dd or start_date < first_date_dd or end_date > last_date_dd or\\\n",
    "\t \t\t\t\t\tend_date < first_date_dd:\n",
    "\t\treturn(f\"Select date range between {first_date[0][0]} and {last_date[0][0]}\")\n",
    "\telse:\n",
    "\t\t#Return a JSON list of the minimum temperature, the average temperature, \n",
    "\t\t#and the max temperature for a given start-end range.\n",
    "\t\tstart_end_min_max_temp = return session.query(func.min(Measurement.tobs), func.avg(Measurement.tobs), func.max(Measurement.tobs)).\\\n",
    "        filter(Measurement.date >= start_date).filter(Measurement.date <= end_date).all()\n",
    "        filter(Measurement.date >= start_date).filter(Measurement.date <= end_date).all()\n",
    "\t\tstart_end_data = list(np.ravel(start_end_min_max_temp))\n",
    "\t\treturn jsonify(start_end_data)\n",
    "if __name__==\"__main__\":\n",
    "\tapp.run(debug=True)"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.7.6"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}
